export const StorageKeys = {
  THEME_MODE: 'THEME_MODE',
  LANGUAGE: 'LANGUAGE',
  ONBOARDING_DONE: 'ONBOARDING_DONE',
  COUNTRY_ISO: 'COUNTRY_ISO',
  PENDING_DRIVER_INVITE_CODE: 'PENDING_DRIVER_INVITE_CODE',
  PENDING_CLIENT_INVITE_CODE: 'PENDING_CLIENT_INVITE_CODE',
};
