import {StyleSheet} from 'react-native';
import {ThemeType} from '@app/theme/theme';
import {LangDirection} from '@app/enums/LangDirection';
import {
  getFlexDirection,
  getTextAlign,
  isRTL,
} from '@app/utils/directionalStyles';
import {cairoFont} from '@app/theme/fonts';
import {elevation, fontSize, radius, space} from '@app/theme/tokens';
import {getHeight, getWidth} from '@app/utils/responsive-design';

export const createOrderStyles = (
  theme: ThemeType,
  direction: LangDirection,
  isDark: boolean,
) => {
  const gold = theme.brand.gold;
  const navy = theme.brand.navy;
  const rtl = isRTL(direction);
  const fieldBg = isDark ? 'rgba(255,255,255,0.045)' : '#F8FAFC';
  const fieldBorder = isDark ? theme.ui.border : '#E2E8F0';

  return StyleSheet.create({
    stack: {
      gap: getHeight(space.sm),
      paddingBottom: getHeight(space.lg),
    },
    hero: {
      gap: getHeight(4),
      marginBottom: getHeight(2),
    },
    heroSubtitle: {
      color: theme.typography.secondary,
      fontSize: fontSize.caption,
      lineHeight: fontSize.caption + 5,
      textAlign: getTextAlign(direction),
      ...cairoFont('regular'),
    },
    tabBar: {
      paddingVertical: getHeight(space.sm),
      paddingHorizontal: getWidth(space.xs),
      backgroundColor: 'transparent',
    },
    tabTrackWrap: {
      position: 'relative',
      paddingTop: getHeight(2),
    },
    tabTrackLine: {
      position: 'absolute',
      top: getWidth(18),
      start: '16%',
      end: '16%',
      borderTopWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: isDark ? theme.ui.border : '#D1D5DB',
    },
    tabRow: {
      flexDirection: getFlexDirection(direction),
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    tab: {
      flex: 1,
      alignItems: 'center',
      gap: getHeight(8),
      paddingHorizontal: getWidth(2),
    },
    tabStep: {
      width: getWidth(36),
      height: getWidth(36),
      borderRadius: getWidth(18),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: isDark ? theme.ui.border : '#D1D5DB',
      backgroundColor: isDark ? theme.backgrounds.surface : '#FFFFFF',
      zIndex: 1,
    },
    tabStepActive: {
      borderColor: navy,
      backgroundColor: navy,
    },
    tabStepNum: {
      color: isDark ? theme.typography.primary : navy,
      fontSize: fontSize.body,
      ...cairoFont('bold'),
    },
    tabStepNumActive: {
      color: '#FFFFFF',
    },
    tabLabel: {
      color: isDark ? theme.typography.primary : navy,
      fontSize: fontSize.body,
      lineHeight: fontSize.body + 2,
      textAlign: 'center',
      ...cairoFont('bold'),
    },
    tabLabelActive: {
      color: isDark ? theme.typography.primary : navy,
      ...cairoFont('bold'),
    },
    tabUnderline: {
      width: getWidth(28),
      height: getHeight(3),
      borderRadius: getHeight(2),
      backgroundColor: 'transparent',
      marginTop: getHeight(-2),
    },
    tabUnderlineActive: {
      backgroundColor: gold,
    },
    sectionCard: {
      backgroundColor: isDark ? theme.backgrounds.surface : '#FFFFFF',
      borderRadius: 18,
      padding: getWidth(14),
      gap: getHeight(12),
      borderWidth: 1,
      borderColor: isDark ? theme.ui.border : '#E8ECF1',
      ...elevation.card,
    },
    panelHeader: {
      flexDirection: getFlexDirection(direction),
      alignItems: 'center',
      gap: getWidth(10),
    },
    panelHeaderIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDark ? 'rgba(212,175,55,0.14)' : 'rgba(15,23,42,0.06)',
    },
    panelHeaderText: {
      flex: 1,
      gap: 2,
    },
    panelTitle: {
      color: isDark ? theme.typography.primary : '#0F172A',
      fontSize: 15,
      lineHeight: 20,
      textAlign: getTextAlign(direction),
      ...cairoFont('bold'),
    },
    panelLead: {
      color: theme.typography.secondary,
      fontSize: 11,
      lineHeight: 16,
      textAlign: getTextAlign(direction),
      ...cairoFont('regular'),
    },
    panelDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: fieldBorder,
      marginVertical: getHeight(2),
    },
    sectionBody: {
      gap: getHeight(space.sm),
    },
    fieldLabel: {
      color: theme.typography.secondary,
      fontSize: fontSize.caption,
      textAlign: getTextAlign(direction),
      ...cairoFont('bold'),
    },
    fieldGroup: {
      gap: getHeight(6),
    },
    fieldBox: {
      minHeight: getHeight(48),
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: fieldBorder,
      backgroundColor: fieldBg,
      paddingHorizontal: getWidth(space.sm),
      flexDirection: getFlexDirection(direction),
      alignItems: 'center',
      gap: getWidth(space.xs),
    },
    fieldInput: {
      flex: 1,
      color: theme.typography.primary,
      fontSize: fontSize.body,
      textAlign: getTextAlign(direction),
      writingDirection: rtl ? 'rtl' : 'ltr',
      paddingVertical: getHeight(10),
      ...cairoFont('medium'),
    },
    chipRow: {
      flexDirection: getFlexDirection(direction),
      gap: getWidth(8),
    },
    chip: {
      flex: 1,
      minHeight: getHeight(42),
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: fieldBorder,
      backgroundColor: fieldBg,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: getWidth(6),
    },
    chipActive: {
      backgroundColor: gold,
      borderColor: gold,
    },
    chipText: {
      color: theme.typography.secondary,
      fontSize: fontSize.label,
      ...cairoFont('medium'),
    },
    chipTextActive: {
      color: navy,
      ...cairoFont('bold'),
    },
    fragileRow: {
      minHeight: getHeight(48),
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: fieldBorder,
      backgroundColor: fieldBg,
      paddingHorizontal: getWidth(space.sm),
      flexDirection: getFlexDirection(direction),
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    fragileRowActive: {
      borderColor: gold,
      backgroundColor: isDark
        ? 'rgba(212, 175, 55, 0.16)'
        : 'rgba(212, 175, 55, 0.12)',
    },
    fragileText: {
      color: theme.typography.primary,
      fontSize: fontSize.body,
      textAlign: getTextAlign(direction),
      ...cairoFont('medium'),
    },
    fragileTextActive: {
      ...cairoFont('bold'),
    },
    fragileDot: {
      width: getWidth(18),
      height: getWidth(18),
      borderRadius: getWidth(9),
      borderWidth: 1.5,
      borderColor: fieldBorder,
      backgroundColor: 'transparent',
    },
    fragileDotActive: {
      borderColor: gold,
      backgroundColor: gold,
    },
    profileToggle: {
      minHeight: getHeight(40),
      borderRadius: 12,
      borderWidth: 1,
      borderColor: fieldBorder,
      backgroundColor: fieldBg,
      paddingHorizontal: getWidth(space.sm),
      flexDirection: getFlexDirection(direction),
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: getWidth(space.xs),
    },
    profileToggleActive: {
      borderColor: gold,
      backgroundColor: isDark
        ? 'rgba(212, 175, 55, 0.16)'
        : 'rgba(212, 175, 55, 0.12)',
    },
    profileToggleText: {
      flex: 1,
      color: theme.typography.primary,
      fontSize: 12,
      textAlign: getTextAlign(direction),
      ...cairoFont('medium'),
    },
    profileToggleTextActive: {
      ...cairoFont('bold'),
    },
    profileToggleDot: {
      width: getWidth(16),
      height: getWidth(16),
      borderRadius: getWidth(8),
      borderWidth: 1.5,
      borderColor: fieldBorder,
      backgroundColor: 'transparent',
    },
    profileToggleDotActive: {
      borderColor: gold,
      backgroundColor: gold,
    },
    locationBody: {
      gap: getHeight(space.xs),
      borderWidth: 1,
      borderColor: fieldBorder,
      borderRadius: radius.md,
      backgroundColor: fieldBg,
      padding: getWidth(space.sm),
    },
    locationTextCol: {
      gap: getHeight(4),
    },
    locationTitle: {
      color: theme.typography.primary,
      fontSize: fontSize.cardTitle,
      lineHeight: fontSize.cardTitle + 6,
      textAlign: getTextAlign(direction),
      ...cairoFont('bold'),
    },
    locationSub: {
      color: theme.typography.secondary,
      fontSize: fontSize.caption,
      lineHeight: fontSize.caption + 4,
      textAlign: getTextAlign(direction),
      ...cairoFont('regular'),
    },
    locationFooter: {
      flexDirection: getFlexDirection(direction),
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: getWidth(space.sm),
      marginTop: getHeight(4),
    },
    pinBadge: {
      width: getWidth(34),
      height: getWidth(34),
      borderRadius: getWidth(17),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.status.success,
    },
    changeBtn: {
      flexDirection: getFlexDirection(direction),
      alignItems: 'center',
      gap: getWidth(2),
      paddingVertical: getHeight(4),
      paddingHorizontal: getWidth(4),
    },
    changeText: {
      color: isDark ? gold : navy,
      fontSize: fontSize.body,
      ...cairoFont('bold'),
    },
    emptySearch: {
      minHeight: getHeight(48),
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: fieldBorder,
      borderStyle: 'dashed',
      backgroundColor: fieldBg,
      paddingHorizontal: getWidth(space.sm),
      flexDirection: getFlexDirection(direction),
      alignItems: 'center',
      gap: getWidth(space.xs),
    },
    emptySearchText: {
      flex: 1,
      color: theme.typography.secondary,
      fontSize: fontSize.body,
      textAlign: getTextAlign(direction),
      ...cairoFont('medium'),
    },
    paymentStack: {
      gap: getHeight(space.sm),
    },
    paymentField: {
      gap: getHeight(6),
    },
    payToggleTrack: {
      minHeight: getHeight(48),
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: fieldBorder,
      backgroundColor: fieldBg,
      padding: getWidth(4),
      flexDirection: getFlexDirection(direction),
      alignItems: 'stretch',
      gap: getWidth(4),
    },
    payToggleOption: {
      flex: 1,
      minHeight: getHeight(38),
      borderRadius: radius.sm,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: getWidth(space.xs),
      paddingVertical: getHeight(6),
    },
    payToggleOptionActive: {
      backgroundColor: gold,
    },
    payToggleText: {
      color: theme.typography.secondary,
      fontSize: fontSize.label,
      textAlign: 'center',
      ...cairoFont('medium'),
    },
    payToggleTextActive: {
      color: navy,
      ...cairoFont('bold'),
    },
    notesBox: {
      minHeight: getHeight(88),
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: fieldBorder,
      backgroundColor: fieldBg,
      paddingHorizontal: getWidth(space.sm),
      paddingVertical: getHeight(space.sm),
    },
    notesInput: {
      flex: 1,
      minHeight: getHeight(64),
      color: theme.typography.primary,
      fontSize: fontSize.body,
      textAlign: getTextAlign(direction),
      writingDirection: rtl ? 'rtl' : 'ltr',
      textAlignVertical: 'top',
      ...cairoFont('medium'),
    },
    /** Pickup card — pixel-tuned to mock */
    panelHeaderIconPickup: {
      backgroundColor: isDark ? 'rgba(232,149,74,0.2)' : '#F6E4D4',
    },
    panelHeaderIconDelivery: {
      backgroundColor: isDark ? 'rgba(232,149,74,0.2)' : '#F6E4D4',
    },
    panelHeaderIconShipment: {
      backgroundColor: isDark ? 'rgba(232,149,74,0.2)' : '#F6E4D4',
    },
    pickupChipRow: {
      flexDirection: 'row',
      gap: 8,
    },
    pickupChip: {
      flex: 1,
      height: 46,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDark ? theme.ui.border : '#E2E8F0',
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : '#FFFFFF',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 6,
    },
    pickupChipActive: {
      borderColor: gold,
      backgroundColor: isDark
        ? 'rgba(212,175,55,0.18)'
        : 'rgba(212,175,55,0.14)',
    },
    pickupChipText: {
      color: '#94A3B8',
      fontSize: 12,
      ...cairoFont('medium'),
    },
    pickupChipTextActive: {
      color: isDark ? gold : navy,
      ...cairoFont('bold'),
    },
    pickupToggleRow: {
      height: 46,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDark ? theme.ui.border : '#E2E8F0',
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : '#FFFFFF',
      paddingHorizontal: 10,
      flexDirection: getFlexDirection(direction),
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    pickupToggleRowActive: {
      borderColor: gold,
      backgroundColor: isDark
        ? 'rgba(212,175,55,0.16)'
        : 'rgba(212,175,55,0.12)',
    },
    pickupToggleText: {
      color: isDark ? theme.typography.primary : '#0F172A',
      fontSize: 12,
      textAlign: getTextAlign(direction),
      ...cairoFont('medium'),
    },
    pickupToggleTextActive: {
      ...cairoFont('bold'),
    },
    pickupToggleDot: {
      width: 16,
      height: 16,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: isDark ? theme.ui.border : '#CBD5E1',
      backgroundColor: 'transparent',
    },
    pickupToggleDotActive: {
      borderColor: gold,
      backgroundColor: gold,
    },
    pickupPayTrack: {
      height: 46,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDark ? theme.ui.border : '#E2E8F0',
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : '#FFFFFF',
      padding: 3,
      flexDirection: getFlexDirection(direction),
      alignItems: 'stretch',
      gap: 3,
    },
    pickupPayOption: {
      flex: 1,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    pickupPayOptionActive: {
      backgroundColor: gold,
    },
    pickupPayText: {
      color: '#94A3B8',
      fontSize: 11,
      textAlign: 'center',
      ...cairoFont('medium'),
    },
    pickupPayTextActive: {
      color: navy,
      ...cairoFont('bold'),
    },
    pickupForm: {
      gap: 10,
    },
    pickupRow: {
      flexDirection: getFlexDirection(direction),
      gap: 8,
      alignItems: 'stretch',
    },
    pickupCol: {
      flex: 1,
      minWidth: 0,
      gap: 5,
    },
    pickupColFull: {
      width: '100%',
      gap: 5,
    },
    pickupLabel: {
      color: isDark ? theme.typography.primary : '#0F172A',
      fontSize: 11,
      lineHeight: 15,
      textAlign: getTextAlign(direction),
      ...cairoFont('bold'),
    },
    pickupField: {
      height: 46,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: isDark ? theme.ui.border : '#E2E8F0',
      backgroundColor: isDark ? 'rgba(255,255,255,0.04)' : '#FFFFFF',
      paddingHorizontal: 10,
      /** Physical LTR row so icons/chevrons match the mock sides. */
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    pickupFieldPressed: {
      borderColor: isDark ? gold : '#94A3B8',
      backgroundColor: isDark ? 'rgba(255,255,255,0.06)' : '#F8FAFC',
    },
    pickupFieldIconSlot: {
      width: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pickupInput: {
      flex: 1,
      minWidth: 0,
      height: '100%',
      color: isDark ? theme.typography.primary : '#0F172A',
      fontSize: 12,
      lineHeight: 16,
      textAlign: getTextAlign(direction),
      writingDirection: rtl ? 'rtl' : 'ltr',
      paddingVertical: 0,
      ...cairoFont('medium'),
    },
    /** Phone digits stay LTR so the full national number stays visible. */
    pickupPhoneInput: {
      flex: 1,
      minWidth: 0,
      height: '100%',
      color: isDark ? theme.typography.primary : '#0F172A',
      fontSize: 13,
      lineHeight: 18,
      textAlign: 'left',
      writingDirection: 'ltr',
      paddingVertical: 0,
      ...cairoFont('medium'),
    },
    pickupValueText: {
      flex: 1,
      minWidth: 0,
      color: isDark ? theme.typography.primary : '#0F172A',
      fontSize: 12,
      lineHeight: 16,
      textAlign: getTextAlign(direction),
      ...cairoFont('medium'),
    },
    pickupPlaceholder: {
      flex: 1,
      minWidth: 0,
      color: '#94A3B8',
      fontSize: 12,
      lineHeight: 16,
      textAlign: getTextAlign(direction),
      ...cairoFont('regular'),
    },
    pickupPhonePrefix: {
      flexDirection: 'row',
      alignItems: 'center',
      flexShrink: 0,
      gap: 4,
      paddingRight: 8,
      marginRight: 2,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: isDark ? theme.ui.border : '#E2E8F0',
    },
    pickupFlag: {
      fontSize: 14,
      lineHeight: 18,
    },
    pickupDial: {
      color: isDark ? theme.typography.primary : '#0F172A',
      fontSize: 12,
      writingDirection: 'ltr',
      ...cairoFont('bold'),
    },
    mapPreviewWrap: {
      height: 118,
      borderRadius: 12,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: isDark ? theme.ui.border : '#E2E8F0',
      backgroundColor: isDark ? fieldBg : '#E8EEF5',
    },
    mapPreview: {
      ...StyleSheet.absoluteFill,
    },
    mapCta: {
      position: 'absolute',
      top: 10,
      right: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      paddingHorizontal: 10,
      paddingVertical: 7,
      shadowColor: '#0F172A',
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: {width: 0, height: 3},
      elevation: 3,
    },
    mapCtaText: {
      color: '#0F172A',
      fontSize: 11,
      ...cairoFont('bold'),
    },
    mapFallback: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: getHeight(6),
      padding: getWidth(space.sm),
    },
    mapFallbackText: {
      color: theme.typography.secondary,
      fontSize: fontSize.caption,
      textAlign: 'center',
      ...cairoFont('regular'),
    },
    submitWrap: {
      marginTop: getHeight(space.xs),
      paddingTop: getHeight(space.xs),
    },
  });
};
